/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bot_zun_animation_by_oscar_creativo.glb --types --shadows --transform --debug 
Files: bot_zun_animation_by_oscar_creativo.glb [12.93MB] > /home/lani/Development/ahiakea/apps/laniakita-com/public/assets/tmp-gltf/bot_zun_animation_by_oscar_creativo-transformed.glb [1.4MB] (89%)
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bot-zun-animation-by-oscar-creativo-c0e0b640363345fa9ac0973d90537978
Title: BOT ZUN ANIMATION by Oscar Creativo
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MANO_IZQ_MANO_IZQ_0: THREE.Mesh
    MANO_DER_MANO_DER_0: THREE.Mesh
    TORNILLO_CABEZA_TORNILLO_CABEZA_0: THREE.Mesh
    HOMBRO_IZQ_HOMBRO_IZQ_0: THREE.Mesh
    HOMNRO_DER_HOMNRO_DER_0: THREE.Mesh
    OJO_OJO_0: THREE.Mesh
    OJO_1_OJO_1_0: THREE.Mesh
    CUERPO__CUERPO__0: THREE.Mesh
    PISO_PISO_0: THREE.Mesh
  }
  materials: {
    MANO_IZQ: THREE.MeshStandardMaterial
    MANO_DER: THREE.MeshStandardMaterial
    TORNILLO_CABEZA: THREE.MeshStandardMaterial
    HOMBRO_IZQ: THREE.MeshStandardMaterial
    HOMNRO_DER: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    OJO_1: THREE.MeshStandardMaterial
    CUERPO: THREE.MeshStandardMaterial
    PISO: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'CINEMA_4D_Principal'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/bot_zun_animation_by_oscar_creativo-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="Nulo_" position={[0, -7.755, 3.109]}>
            <group name="MANO_IZQ" position={[-55.287, 34.915, -0.5]}>
              <mesh name="MANO_IZQ_MANO_IZQ_0" castShadow receiveShadow geometry={nodes.MANO_IZQ_MANO_IZQ_0.geometry} material={materials.MANO_IZQ} />
            </group>
            <group name="MANO_DER" position={[54.225, 35.376, -0.263]}>
              <mesh name="MANO_DER_MANO_DER_0" castShadow receiveShadow geometry={nodes.MANO_DER_MANO_DER_0.geometry} material={materials.MANO_DER} />
            </group>
            <group name="TORNILLO_CABEZA" position={[0, 70.112, 0.092]}>
              <mesh name="TORNILLO_CABEZA_TORNILLO_CABEZA_0" castShadow receiveShadow geometry={nodes.TORNILLO_CABEZA_TORNILLO_CABEZA_0.geometry} material={materials.TORNILLO_CABEZA} />
            </group>
            <group name="HOMBRO_IZQ" position={[-43.492, 35.439, -0.026]}>
              <mesh name="HOMBRO_IZQ_HOMBRO_IZQ_0" castShadow receiveShadow geometry={nodes.HOMBRO_IZQ_HOMBRO_IZQ_0.geometry} material={materials.HOMBRO_IZQ} />
            </group>
            <group name="HOMNRO_DER" position={[42.533, 34.02, -3.109]}>
              <mesh name="HOMNRO_DER_HOMNRO_DER_0" castShadow receiveShadow geometry={nodes.HOMNRO_DER_HOMNRO_DER_0.geometry} material={materials.HOMNRO_DER} />
            </group>
            <group name="OJO" position={[14.132, 34.19, 43.244]}>
              <mesh name="OJO_OJO_0" castShadow receiveShadow geometry={nodes.OJO_OJO_0.geometry} material={materials.material} />
            </group>
            <group name="OJO_1" position={[-17.524, 35.207, 41.548]}>
              <mesh name="OJO_1_OJO_1_0" castShadow receiveShadow geometry={nodes.OJO_1_OJO_1_0.geometry} material={materials.OJO_1} />
            </group>
            <group name="CUERPO_" position={[0, 0.52, -3.109]}>
              <mesh name="CUERPO__CUERPO__0" castShadow receiveShadow geometry={nodes.CUERPO__CUERPO__0.geometry} material={materials.CUERPO} />
            </group>
          </group>
          <group name="PISO" position={[0, -11.955, 0]}>
            <mesh name="PISO_PISO_0" castShadow receiveShadow geometry={nodes.PISO_PISO_0.geometry} material={materials.PISO} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bot_zun_animation_by_oscar_creativo-transformed.glb')
