// @ts-nocheck -- skip type checking
import * as post_5 from "../content/posts/2025/02/fixing-my-ci-an-adventure-with-turborepo-sst-and-bun.mdx?collection=post&hash=1740711812958"
import * as post_4 from "../content/posts/2025/01/nixos-fde-tpm-hm-guide.mdx?collection=post&hash=1740711812958"
import * as post_3 from "../content/posts/2024/10/how-i-built-my-own-cms-complete.mdx?collection=post&hash=1740711812958"
import * as post_2 from "../content/posts/2024/08/thoughts-on-rebuilding-my-personal-website.mdx?collection=post&hash=1740711812958"
import * as post_1 from "../content/posts/2024/05/welcome-to-yet-another-dev-blog.mdx?collection=post&hash=1740711812958"
import * as post_0 from "../content/posts/2024/05/bot-clicker.mdx?collection=post&hash=1740711812958"
import * as tag_6 from "../content/tags/turborepo.mdx?collection=tag&hash=1740711812958"
import * as tag_5 from "../content/tags/sst.mdx?collection=tag&hash=1740711812958"
import * as tag_4 from "../content/tags/rss.mdx?collection=tag&hash=1740711812958"
import * as tag_3 from "../content/tags/nix-nixos.mdx?collection=tag&hash=1740711812958"
import * as tag_2 from "../content/tags/next-js.mdx?collection=tag&hash=1740711812958"
import * as tag_1 from "../content/tags/drizzle-orm.mdx?collection=tag&hash=1740711812958"
import * as tag_0 from "../content/tags/bun.mdx?collection=tag&hash=1740711812958"
import * as category_6 from "../content/categories/technical-summary.mdx?collection=category&hash=1740711812958"
import * as category_5 from "../content/categories/security.mdx?collection=category&hash=1740711812958"
import * as category_4 from "../content/categories/meta.mdx?collection=category&hash=1740711812958"
import * as category_3 from "../content/categories/linux.mdx?collection=category&hash=1740711812958"
import * as category_2 from "../content/categories/guides.mdx?collection=category&hash=1740711812958"
import * as category_1 from "../content/categories/full-stack.mdx?collection=category&hash=1740711812958"
import * as category_0 from "../content/categories/backend.mdx?collection=category&hash=1740711812958"
import * as author_0 from "../content/authors/lani.mdx?collection=author&hash=1740711812958"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const author = _runtime.doc<typeof _source.author>([{ info: {"path":"lani.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/authors/lani.mdx"}, data: author_0 }]);
export const category = _runtime.doc<typeof _source.category>([{ info: {"path":"backend.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/backend.mdx"}, data: category_0 }, { info: {"path":"full-stack.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/full-stack.mdx"}, data: category_1 }, { info: {"path":"guides.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/guides.mdx"}, data: category_2 }, { info: {"path":"linux.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/linux.mdx"}, data: category_3 }, { info: {"path":"meta.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/meta.mdx"}, data: category_4 }, { info: {"path":"security.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/security.mdx"}, data: category_5 }, { info: {"path":"technical-summary.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/categories/technical-summary.mdx"}, data: category_6 }]);
export const post = _runtime.doc<typeof _source.post>([{ info: {"path":"2024/05/bot-clicker.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/posts/2024/05/bot-clicker.mdx"}, data: post_0 }, { info: {"path":"2024/05/welcome-to-yet-another-dev-blog.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/posts/2024/05/welcome-to-yet-another-dev-blog.mdx"}, data: post_1 }, { info: {"path":"2024/08/thoughts-on-rebuilding-my-personal-website.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/posts/2024/08/thoughts-on-rebuilding-my-personal-website.mdx"}, data: post_2 }, { info: {"path":"2024/10/how-i-built-my-own-cms-complete.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/posts/2024/10/how-i-built-my-own-cms-complete.mdx"}, data: post_3 }, { info: {"path":"2025/01/nixos-fde-tpm-hm-guide.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/posts/2025/01/nixos-fde-tpm-hm-guide.mdx"}, data: post_4 }, { info: {"path":"2025/02/fixing-my-ci-an-adventure-with-turborepo-sst-and-bun.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/posts/2025/02/fixing-my-ci-an-adventure-with-turborepo-sst-and-bun.mdx"}, data: post_5 }]);
export const tag = _runtime.doc<typeof _source.tag>([{ info: {"path":"bun.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/bun.mdx"}, data: tag_0 }, { info: {"path":"drizzle-orm.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/drizzle-orm.mdx"}, data: tag_1 }, { info: {"path":"next-js.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/next-js.mdx"}, data: tag_2 }, { info: {"path":"nix-nixos.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/nix-nixos.mdx"}, data: tag_3 }, { info: {"path":"rss.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/rss.mdx"}, data: tag_4 }, { info: {"path":"sst.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/sst.mdx"}, data: tag_5 }, { info: {"path":"turborepo.mdx","absolutePath":"/home/lani/Development/website/apps/web/content/tags/turborepo.mdx"}, data: tag_6 }]);