/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as coreRouteRouteImport } from './routes/(core)/route'
import { Route as coreIndexRouteImport } from './routes/(core)/index'
import { Route as coreBlogMetaRouteImport } from './routes/(core)/_blog-meta'
import { Route as coreInfoRouteImport } from './routes/(core)/_info'
import { Route as coreWorkRouteImport } from './routes/(core)/work'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as OpengraphSplatRouteImport } from './routes/opengraph/$'
import { Route as coreInfoSplatRouteImport } from './routes/(core)/_info.$'
import { Route as coreBlogMetaCategoriesSlugRouteImport } from './routes/(core)/_blog-meta.categories.$slug'
import { Route as coreBlogMetaTagsSlugRouteImport } from './routes/(core)/_blog-meta.tags.$slug'

const coreRouteRoute = coreRouteRouteImport.update({
  id: '/(core)',
  getParentRoute: () => rootRouteImport,
} as any)
const coreIndexRoute = coreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreBlogMetaRoute = coreBlogMetaRouteImport.update({
  id: '/_blog-meta',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreInfoRoute = coreInfoRouteImport.update({
  id: '/_info',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreWorkRoute = coreWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => coreRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphSplatRoute = OpengraphSplatRouteImport.update({
  id: '/opengraph/$',
  path: '/opengraph/$',
  getParentRoute: () => rootRouteImport,
} as any)
const coreInfoSplatRoute = coreInfoSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => coreInfoRoute,
} as any)
const coreBlogMetaCategoriesSlugRoute =
  coreBlogMetaCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => coreBlogMetaRoute,
  } as any)
const coreBlogMetaTagsSlugRoute = coreBlogMetaTagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => coreBlogMetaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/work': typeof coreWorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/opengraph/$': typeof OpengraphSplatRoute
  '/': typeof coreIndexRoute
  '/$': typeof coreInfoSplatRoute
  '/categories/$slug': typeof coreBlogMetaCategoriesSlugRoute
  '/tags/$slug': typeof coreBlogMetaTagsSlugRoute
}
export interface FileRoutesByTo {
  '/work': typeof coreWorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/opengraph/$': typeof OpengraphSplatRoute
  '/': typeof coreIndexRoute
  '/$': typeof coreInfoSplatRoute
  '/categories/$slug': typeof coreBlogMetaCategoriesSlugRoute
  '/tags/$slug': typeof coreBlogMetaTagsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(core)': typeof coreRouteRouteWithChildren
  '/(core)/_blog-meta': typeof coreBlogMetaRouteWithChildren
  '/(core)/_info': typeof coreInfoRouteWithChildren
  '/(core)/work': typeof coreWorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/opengraph/$': typeof OpengraphSplatRoute
  '/(core)/': typeof coreIndexRoute
  '/(core)/_info/$': typeof coreInfoSplatRoute
  '/(core)/_blog-meta/categories/$slug': typeof coreBlogMetaCategoriesSlugRoute
  '/(core)/_blog-meta/tags/$slug': typeof coreBlogMetaTagsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/work'
    | '/blog/$slug'
    | '/opengraph/$'
    | '/'
    | '/$'
    | '/categories/$slug'
    | '/tags/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/work'
    | '/blog/$slug'
    | '/opengraph/$'
    | '/'
    | '/$'
    | '/categories/$slug'
    | '/tags/$slug'
  id:
    | '__root__'
    | '/(core)'
    | '/(core)/_blog-meta'
    | '/(core)/_info'
    | '/(core)/work'
    | '/blog/$slug'
    | '/opengraph/$'
    | '/(core)/'
    | '/(core)/_info/$'
    | '/(core)/_blog-meta/categories/$slug'
    | '/(core)/_blog-meta/tags/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  coreRouteRoute: typeof coreRouteRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  OpengraphSplatRoute: typeof OpengraphSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(core)': {
      id: '/(core)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/': {
      id: '/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/_blog-meta': {
      id: '/(core)/_blog-meta'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreBlogMetaRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/_info': {
      id: '/(core)/_info'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreInfoRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/work': {
      id: '/(core)/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof coreWorkRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph/$': {
      id: '/opengraph/$'
      path: '/opengraph/$'
      fullPath: '/opengraph/$'
      preLoaderRoute: typeof OpengraphSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/_info/$': {
      id: '/(core)/_info/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof coreInfoSplatRouteImport
      parentRoute: typeof coreInfoRoute
    }
    '/(core)/_blog-meta/categories/$slug': {
      id: '/(core)/_blog-meta/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof coreBlogMetaCategoriesSlugRouteImport
      parentRoute: typeof coreBlogMetaRoute
    }
    '/(core)/_blog-meta/tags/$slug': {
      id: '/(core)/_blog-meta/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof coreBlogMetaTagsSlugRouteImport
      parentRoute: typeof coreBlogMetaRoute
    }
  }
}

interface coreBlogMetaRouteChildren {
  coreBlogMetaCategoriesSlugRoute: typeof coreBlogMetaCategoriesSlugRoute
  coreBlogMetaTagsSlugRoute: typeof coreBlogMetaTagsSlugRoute
}

const coreBlogMetaRouteChildren: coreBlogMetaRouteChildren = {
  coreBlogMetaCategoriesSlugRoute: coreBlogMetaCategoriesSlugRoute,
  coreBlogMetaTagsSlugRoute: coreBlogMetaTagsSlugRoute,
}

const coreBlogMetaRouteWithChildren = coreBlogMetaRoute._addFileChildren(
  coreBlogMetaRouteChildren,
)

interface coreInfoRouteChildren {
  coreInfoSplatRoute: typeof coreInfoSplatRoute
}

const coreInfoRouteChildren: coreInfoRouteChildren = {
  coreInfoSplatRoute: coreInfoSplatRoute,
}

const coreInfoRouteWithChildren = coreInfoRoute._addFileChildren(
  coreInfoRouteChildren,
)

interface coreRouteRouteChildren {
  coreBlogMetaRoute: typeof coreBlogMetaRouteWithChildren
  coreInfoRoute: typeof coreInfoRouteWithChildren
  coreWorkRoute: typeof coreWorkRoute
  coreIndexRoute: typeof coreIndexRoute
}

const coreRouteRouteChildren: coreRouteRouteChildren = {
  coreBlogMetaRoute: coreBlogMetaRouteWithChildren,
  coreInfoRoute: coreInfoRouteWithChildren,
  coreWorkRoute: coreWorkRoute,
  coreIndexRoute: coreIndexRoute,
}

const coreRouteRouteWithChildren = coreRouteRoute._addFileChildren(
  coreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  coreRouteRoute: coreRouteRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  OpengraphSplatRoute: OpengraphSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
