/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as coreRouteRouteImport } from './routes/(core)/route'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as OpengraphRouteImport } from './routes/opengraph'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as coreIndexRouteImport } from './routes/(core)/index'
import { Route as coreBlogMetaRouteImport } from './routes/(core)/_blog-meta'
import { Route as coreInfoRouteImport } from './routes/(core)/_info'
import { Route as coreWorkRouteImport } from './routes/(core)/work'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as coreInfoSplatRouteImport } from './routes/(core)/_info.$'
import { Route as coreBlogMetaCategoriesSlugRouteImport } from './routes/(core)/_blog-meta.categories.$slug'
import { Route as coreBlogMetaTagsSlugRouteImport } from './routes/(core)/_blog-meta.tags.$slug'
import { Route as WorksShadersNoise01RouteImport } from './routes/works/shaders.noise.01'

const coreRouteRoute = coreRouteRouteImport.update({
  id: '/(core)',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphRoute = OpengraphRouteImport.update({
  id: '/opengraph',
  path: '/opengraph',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const coreIndexRoute = coreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreBlogMetaRoute = coreBlogMetaRouteImport.update({
  id: '/_blog-meta',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreInfoRoute = coreInfoRouteImport.update({
  id: '/_info',
  getParentRoute: () => coreRouteRoute,
} as any)
const coreWorkRoute = coreWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => coreRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const coreInfoSplatRoute = coreInfoSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => coreInfoRoute,
} as any)
const coreBlogMetaCategoriesSlugRoute =
  coreBlogMetaCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => coreBlogMetaRoute,
  } as any)
const coreBlogMetaTagsSlugRoute = coreBlogMetaTagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => coreBlogMetaRoute,
} as any)
const WorksShadersNoise01Route = WorksShadersNoise01RouteImport.update({
  id: '/works/shaders/noise/01',
  path: '/works/shaders/noise/01',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/atom.xml': typeof AtomDotxmlRoute
  '/opengraph': typeof OpengraphRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof coreWorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/': typeof coreIndexRoute
  '/$': typeof coreInfoSplatRoute
  '/categories/$slug': typeof coreBlogMetaCategoriesSlugRoute
  '/tags/$slug': typeof coreBlogMetaTagsSlugRoute
  '/works/shaders/noise/01': typeof WorksShadersNoise01Route
}
export interface FileRoutesByTo {
  '/atom.xml': typeof AtomDotxmlRoute
  '/opengraph': typeof OpengraphRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof coreWorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/': typeof coreIndexRoute
  '/$': typeof coreInfoSplatRoute
  '/categories/$slug': typeof coreBlogMetaCategoriesSlugRoute
  '/tags/$slug': typeof coreBlogMetaTagsSlugRoute
  '/works/shaders/noise/01': typeof WorksShadersNoise01Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(core)': typeof coreRouteRouteWithChildren
  '/atom.xml': typeof AtomDotxmlRoute
  '/opengraph': typeof OpengraphRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(core)/_blog-meta': typeof coreBlogMetaRouteWithChildren
  '/(core)/_info': typeof coreInfoRouteWithChildren
  '/(core)/work': typeof coreWorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/(core)/': typeof coreIndexRoute
  '/(core)/_info/$': typeof coreInfoSplatRoute
  '/(core)/_blog-meta/categories/$slug': typeof coreBlogMetaCategoriesSlugRoute
  '/(core)/_blog-meta/tags/$slug': typeof coreBlogMetaTagsSlugRoute
  '/works/shaders/noise/01': typeof WorksShadersNoise01Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/atom.xml'
    | '/opengraph'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/work'
    | '/blog/$slug'
    | '/'
    | '/$'
    | '/categories/$slug'
    | '/tags/$slug'
    | '/works/shaders/noise/01'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atom.xml'
    | '/opengraph'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/work'
    | '/blog/$slug'
    | '/'
    | '/$'
    | '/categories/$slug'
    | '/tags/$slug'
    | '/works/shaders/noise/01'
  id:
    | '__root__'
    | '/(core)'
    | '/atom.xml'
    | '/opengraph'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(core)/_blog-meta'
    | '/(core)/_info'
    | '/(core)/work'
    | '/blog/$slug'
    | '/(core)/'
    | '/(core)/_info/$'
    | '/(core)/_blog-meta/categories/$slug'
    | '/(core)/_blog-meta/tags/$slug'
    | '/works/shaders/noise/01'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  coreRouteRoute: typeof coreRouteRouteWithChildren
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  OpengraphRoute: typeof OpengraphRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  WorksShadersNoise01Route: typeof WorksShadersNoise01Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(core)': {
      id: '/(core)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph': {
      id: '/opengraph'
      path: '/opengraph'
      fullPath: '/opengraph'
      preLoaderRoute: typeof OpengraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/': {
      id: '/(core)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof coreIndexRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/_blog-meta': {
      id: '/(core)/_blog-meta'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreBlogMetaRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/_info': {
      id: '/(core)/_info'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreInfoRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/(core)/work': {
      id: '/(core)/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof coreWorkRouteImport
      parentRoute: typeof coreRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/_info/$': {
      id: '/(core)/_info/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof coreInfoSplatRouteImport
      parentRoute: typeof coreInfoRoute
    }
    '/(core)/_blog-meta/categories/$slug': {
      id: '/(core)/_blog-meta/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof coreBlogMetaCategoriesSlugRouteImport
      parentRoute: typeof coreBlogMetaRoute
    }
    '/(core)/_blog-meta/tags/$slug': {
      id: '/(core)/_blog-meta/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof coreBlogMetaTagsSlugRouteImport
      parentRoute: typeof coreBlogMetaRoute
    }
    '/works/shaders/noise/01': {
      id: '/works/shaders/noise/01'
      path: '/works/shaders/noise/01'
      fullPath: '/works/shaders/noise/01'
      preLoaderRoute: typeof WorksShadersNoise01RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface coreBlogMetaRouteChildren {
  coreBlogMetaCategoriesSlugRoute: typeof coreBlogMetaCategoriesSlugRoute
  coreBlogMetaTagsSlugRoute: typeof coreBlogMetaTagsSlugRoute
}

const coreBlogMetaRouteChildren: coreBlogMetaRouteChildren = {
  coreBlogMetaCategoriesSlugRoute: coreBlogMetaCategoriesSlugRoute,
  coreBlogMetaTagsSlugRoute: coreBlogMetaTagsSlugRoute,
}

const coreBlogMetaRouteWithChildren = coreBlogMetaRoute._addFileChildren(
  coreBlogMetaRouteChildren,
)

interface coreInfoRouteChildren {
  coreInfoSplatRoute: typeof coreInfoSplatRoute
}

const coreInfoRouteChildren: coreInfoRouteChildren = {
  coreInfoSplatRoute: coreInfoSplatRoute,
}

const coreInfoRouteWithChildren = coreInfoRoute._addFileChildren(
  coreInfoRouteChildren,
)

interface coreRouteRouteChildren {
  coreBlogMetaRoute: typeof coreBlogMetaRouteWithChildren
  coreInfoRoute: typeof coreInfoRouteWithChildren
  coreWorkRoute: typeof coreWorkRoute
  coreIndexRoute: typeof coreIndexRoute
}

const coreRouteRouteChildren: coreRouteRouteChildren = {
  coreBlogMetaRoute: coreBlogMetaRouteWithChildren,
  coreInfoRoute: coreInfoRouteWithChildren,
  coreWorkRoute: coreWorkRoute,
  coreIndexRoute: coreIndexRoute,
}

const coreRouteRouteWithChildren = coreRouteRoute._addFileChildren(
  coreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  coreRouteRoute: coreRouteRouteWithChildren,
  AtomDotxmlRoute: AtomDotxmlRoute,
  OpengraphRoute: OpengraphRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  WorksShadersNoise01Route: WorksShadersNoise01Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
